from enum import StrEnum


class ErrorCode(StrEnum):
    VCENTER_NOT_CONFIGURED = "VCENTER_NOT_CONFIGURED"
    VCENTER_AUTH_FAILED = "VCENTER_AUTH_FAILED"
    VCENTER_SESSION_EXPIRED = "VCENTER_SESSION_EXPIRED"
    VCENTER_UNREACHABLE = "VCENTER_UNREACHABLE"
    VCENTER_SSL_ERROR = "VCENTER_SSL_ERROR"
    VCENTER_INVENTORY_ERROR = "VCENTER_INVENTORY_ERROR"
    VM_NOT_FOUND = "VM_NOT_FOUND"
    HOST_NOT_FOUND = "HOST_NOT_FOUND"
    DATASTORE_NOT_FOUND = "DATASTORE_NOT_FOUND"
    WRONG_OBJECT_TYPE = "WRONG_OBJECT_TYPE"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_DISABLED = "TOOL_DISABLED"
    TOOL_NOT_IMPLEMENTED = "TOOL_NOT_IMPLEMENTED"
    TOOL_REQUIRES_APPROVAL = "TOOL_REQUIRES_APPROVAL"
    TOOL_POLICY_BLOCKED = "TOOL_POLICY_BLOCKED"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    MCP_SERVER_UNAVAILABLE = "MCP_SERVER_UNAVAILABLE"
    MCP_SERVER_NOT_FOUND = "MCP_SERVER_NOT_FOUND"
    MCP_DISCOVERY_FAILED = "MCP_DISCOVERY_FAILED"
    MCP_TOOL_NOT_FOUND = "MCP_TOOL_NOT_FOUND"
    MCP_TOOL_BLOCKED = "MCP_TOOL_BLOCKED"
    MCP_TOOL_EXECUTION_FAILED = "MCP_TOOL_EXECUTION_FAILED"
    MCP_TOOL_INVALID_INPUT = "MCP_TOOL_INVALID_INPUT"
    INTERNAL_ERROR = "INTERNAL_ERROR"


AUTH_FAILURE_CODES = {
    ErrorCode.VCENTER_AUTH_FAILED,
    ErrorCode.VCENTER_SESSION_EXPIRED,
    ErrorCode.VCENTER_SSL_ERROR,
}

POLICY_FAILURE_CODES = {
    ErrorCode.TOOL_DISABLED,
    ErrorCode.TOOL_NOT_IMPLEMENTED,
    ErrorCode.TOOL_REQUIRES_APPROVAL,
    ErrorCode.TOOL_POLICY_BLOCKED,
}
