apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjs
  namespace: agentic-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - infra-agent-console.dclab.local
      secretName: app-tls
  rules:
    - host: infra-agent-console.dclab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjs
                port:
                  number: 3000
